# Setup
name:         45°中心
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "zh"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page/:num/"
#Others
markdown: kramdown
