# Setup
name:         Project or Site name (Architect Theme)
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"
paginate: 5
paginate_path: "page:num"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
